### ISSUE TITLE
 CocoaPods could not find compatible versions for pod "Firebase/Installations":

### ISSUE THREAD

**Issue by Abdulrehman53** [lidio601/flutter_installations#1]
CocoaPods could not find compatible versions for pod "Firebase/Installations": 

None of your spec sources contain a spec satisfying the dependency: `Firebase/Installations (= 6.33.0)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by lidio601** [comment]
The firebase version 6.33.0 is not hardcoded anywhere.
I think it's coming from your app's Podfile as in my podfile I refer to the variable [FirebaseSDKVersion](https://github.com/lidio601/flutter_installations/blob/main/ios/firebase_installations.podspec#L6).

Hope that helps
